import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
/* Move client-only toggle into a separate Client Component */
/* ThemeToggle removed to keep site permanently in light mode */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* Server Component layout; renders a Client ThemeToggle inside header */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen section-pad">
          <header className="header-gradient section-pad mb-4">
            <div className="container" style={{ position: "relative" }}>
              <h1 className="text-2xl font-bold" style={{ color: "#fff" }}>
                Sai Ram Hostel
              </h1>
              <p className="mt-1" style={{ color: "rgba(255,255,255,0.9)" }}>
                Manage rooms, customers and dues with a clean and colorful UI
              </p>

              {/* Theme toggle removed to keep permanent white theme */}
            </div>
          </header>

          <main className="container grid gap-4">
            <section className="card section-pad">
              {children}
            </section>

            <section className="card section-pad">
              <h2 className="text-lg font-semibold" style={{ color: "var(--foreground)" }}>
                Notes
              </h2>
              <p className="mt-1" style={{ color: "var(--muted-foreground)" }}>
                Use these section cards to separate content and improve readability.
              </p>
            </section>
          </main>

          <footer className="container section-pad" style={{ color: "var(--muted-foreground)" }}>
            © {new Date().getFullYear()} Sai Ram Hostel
          </footer>
        </div>
      </body>
    </html>
  );
}
